name: "school_climate"
version: "1.0.0"
config-version: 2

profile: "school_climate_profile"

model-paths: ["models"]
seed-paths: ["seeds"]
test-paths: ["tests"]
analysis-paths: ["analysis"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets: ["target", "dbt_packages"]

models:
  school_climate:
    svi:
      bronze:
        +schema: "BRONZE"
        +materialized: view

      silver:
        +schema: "SILVER"
        +materialized: table

      gold:
        +schema: "GOLD"
        +materialized: table

# Seed configuration
seeds:
  school_climate:          # MUST match project name at top
    +schema: "GOLD"        # default seed schema for this project
    +quote_columns: false

    svi:                   # matches seeds/svi/
      +schema: "GOLD"
      dim_svi_definition:  # matches seeds/svi/dim_svi_definition.csv
        +schema: "GOLD"

    climate:               # matches seeds/climate/
      +schema: "GOLD"
      dim_climate_metric_definition:   # seeds/climate/dim_climate_metric_definition.csv
        +schema: "GOLD"
      dim_climate_question:           # seeds/climate/dim_climate_question.csv
        +schema: "GOLD"
