CREATE ROLE IF NOT EXISTS PIPELINE_ROLE;

GRANT USAGE ON DATABASE SCHOOL_CLIMATE TO ROLE PIPELINE_ROLE;
GRANT USAGE ON ALL SCHEMAS IN DATABASE SCHOOL_CLIMATE TO ROLE PIPELINE_ROLE;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA SCHOOL_CLIMATE.BRONZE TO ROLE PIPELINE_ROLE;
